#! /usr/bin/env python
"""A script that will generate tags for a git project in the .git folder. Could
be used in git hooks like so:
http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

Or some other way. Whatever.
"""

import os
import sys
import shlex
from subprocess import Popen, PIPE


temp_tags_filename = "{}/tags.temp"
tags_filename = "{}/tags"
ctags_command = "ctags -R -o {} {}"
git_dir_command = 'git rev-parse --git-dir'


def run_command(command):
    tokenized_command = shlex.split(command)
    p = Popen(tokenized_command, stdout=PIPE, stderr=PIPE)
    stdout = p.stdout.read()
    return stdout.rstrip()

git_dir = run_command(git_dir_command).decode('u8')

if not git_dir:
    sys.exit(1)

temp_tags_filename = temp_tags_filename.format(git_dir)
tags_filename = tags_filename.format(git_dir)
ctags_command = ctags_command.format(temp_tags_filename, git_dir + '/..')

try:
    # remove the old temp file if for whatever reason it's still there
    os.remove(temp_tags_filename)
except OSError:
    pass

run_command(ctags_command.format(temp_tags_filename, git_dir + '/..'))
os.rename(temp_tags_filename, tags_filename)
