#! /usr/bin/env python
'''A script that will generate tags for a project in the .git folder.

I use it in vim on each write like so:

    if executable('ctags') && executable('ctags')
        augroup tags
            au BufWritePost *.py,*.c call system('git-tags')
        augroup END
    endif
'''

import os
import shlex
import sys
from subprocess import Popen, PIPE


def run_command(command):
    '''Run a command and return the stdout content.'''
    tokenized_command = shlex.split(command)
    p = Popen(tokenized_command, stdout=PIPE, stderr=PIPE)
    return p.stdout.read().rstrip()


project_dir = run_command('git rev-parse --show-toplevel').decode('u8')
git_dir = os.path.join(project_dir, '.git')

if not project_dir:
    sys.exit(1)

tags_path = os.path.join(git_dir, 'tags')
tmp_tags_path = os.path.join(git_dir, 'tags.tmp')

try:
    # remove the old temp file if for whatever reason it's still there
    os.remove(tmp_tags_path)
except OSError:
    pass

ctags_command = 'ctags -R -o %s %s' % (tmp_tags_path, project_dir)
run_command(ctags_command)
os.rename(tmp_tags_path, tags_path)
