#!/usr/bin/python
import subprocess
import shlex


def git_command(command):
    command = command
    tokenized_command = shlex.split(command)

    p = subprocess.Popen(tokenized_command,
                         stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)

    stdout = p.stdout.read()
    return stdout

branch = git_command('git rev-parse --abbrev-ref HEAD')
dirty = git_command('git status --porcelain')

if branch:
    # branch[:-1] to slice up until '\n'
    print ' ({}{})'.format(branch[:-1], '*' if dirty else '')
