#!/usr/bin/python
"""A script for use in a bash prompt, will show the current git branch.  If you
export a ENV variable COLORS it will also show the branch in red if the branch
is dirty, and green otherwise"""

import os
import shlex
import subprocess

colors = {
    'HEADER': '\033[95m',
    'OKBLUE': '\033[94m',
    'OKGREEN': '\033[92m',
    'WARNING': '\033[93m',
    'FAIL': '\033[91m',
    'ENDC': '\033[0m',
    'BOLD': '\033[1m',
    'UNDERLINE': '\033[4m',
}


def git_command(command):
    command = command
    tokenized_command = shlex.split(command)

    p = subprocess.Popen(tokenized_command,
                         stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)

    stdout = p.stdout.read()
    return stdout

branch = git_command('git rev-parse --abbrev-ref HEAD')
dirty = git_command('git status --porcelain')

if branch:
    prompt = ' git:'
    if os.getenv('COLORS'):
        prompt += colors['FAIL'] if dirty else colors['OKGREEN']
        # branch[:-1] to slice up until '\n'
        prompt += branch[:-1]
        prompt += colors['ENDC']
    else:
        prompt += '{}{}'.format(branch[:-1], '*' if dirty else '')

    print prompt
