#!/usr/bin/env bash
_INPUT_FILE=$(mktemp)
i3-sensible-terminal -c "scratch-i3-input-window" vim -c "set noswapfile" "$_INPUT_FILE"
# strip last byte, the newline. https://stackoverflow.com/a/12579554
head -c -1 $_INPUT_FILE | xdotool type --clearmodifiers --delay 0 --file -
rm $_INPUT_FILE
