#!/usr/bin/env python3

# NOTE WIP! has not been tested

import i3ipc


def main(conn):
    for workspace in conn.get_workspaces():
        # workspaces wrap so right of right is left
        conn.command('[workspace="%s"] move workspace to output right'
                     % workspace['name'])


if __name__ == '__main__':
    conn = i3ipc.Connection()
    main(conn)
