#!/bin/bash

# ONLY RUN THIS IF YOU CAN TRUST THE PEOPLE ON YOUR NETWORK!!!! Opens
# a port so others on the netwerk so others can access it. Best if you
# specify an ip address, otherwise it's open to all. Wrote this so
# others can checkout my dev server.

SCRIPT=`basename "$0"`
USAGE="$SCRIPT [-d] [-s <ipaddr>] port"

while [[ $# > 1 ]]; do
	case $1 in
		-d|-D)
			OPTION="-D"
			shift
			;;
		-s)
			IP="-s $2"
			shift 2
			;;
		*)
			echo "$USAGE"
			exit 1
	esac
done

if [[ ! "$1" =~ ^[0-9]+$ ]]; then
	echo "$USAGE"
	exit 1
else
	PORT="$1"
fi

sudo /sbin/iptables "$OPTION" INPUT -p tcp "$IP" --dport "$PORT" -j ACCEPT
