[ids]

*

[main]

# Maps capslock and capslock to escape when pressed and control when held.
control = overload(control, esc)
capslock = overload(control, esc)

space = overloadt(symbols, space, 200)
backspace = overloadt(symbols, backspace, 200)

a = lettermod(control, a, 150, 200)
s = lettermod(shift, s, 150, 200)
d = lettermod(meta, d, 150, 200)
f = lettermod(alt, f, 150, 200)
j = lettermod(alt, j, 150, 200)
k = lettermod(meta, k, 150, 200)
l = lettermod(shift, l, 150, 200)
; = lettermod(control, ;, 150, 200)
v = lettermod(altgr, v, 150, 200)
m = lettermod(altgr, m, 150, 200)

[symbols]
w = \
e = [
r = ]
t = |

d = (
f = )
g = `

x = /
c = {
v = }
b = ~

y = *
u = -
i = +

h = '
j = =
k = !

n = "
m = _
, = <
. = >
