[global]
oneshot_timeout = 250
chord_timeout = 15

[ids]
*

[main]

u+i = :
j+k = equal
equal = +
m+, = _
h+j = "
n+m = |
d+f = {
f+g = }

1 = !
2 = @
3 = #
4 = $
5 = %
6 = ^
7 = &
8 = *
9 = (
0 = )

a = lettermod(meta, a, 110, 200)
s = lettermod(shift, s, 110, 200)
d = lettermod(alt, d, 110, 200)
f = lettermod(control, f, 110, 200)

j = lettermod(control, j, 110, 200)
k = lettermod(alt, k, 110, 200)
l = lettermod(shift, l, 110, 200)
; = lettermod(meta, ;, 110, 200)

leftcontrol = overload(control, escape)

leftshift = oneshot(shift)
rightshift = oneshot(shift)

# I like these from readline
[control]
m = enter
i = tab

[meta]
1 = M-1
2 = M-2
3 = M-3
4 = M-4
5 = M-5
6 = M-6
7 = M-7
8 = M-8
9 = M-9
0 = M-0

[shift]
leftshift = {
rightshift = }

1 = 1
2 = 2
3 = 3
4 = 4
5 = 5
6 = 6
7 = 7
8 = 8
9 = 9
0 = 0
equal = ~

[symbols]
e = [
r = ]
t = |

d = (
f = )
g = `

c = {
v = }
b = ~

y = *
u = -
i = +

h = '
j = =
k = !
; = :

n = "
m = _
, = <
. = >
/ = ?

1 = !
2 = @
3 = #
4 = $
5 = %
6 = ^
7 = &
8 = *
9 = (
0 = )

[keypad]
m = 1
, = 2
. = 3
j = 4
k = 5
l = 6
u = 7
i = 8
o = 9
n = 0
8 = =
9 = /
0 = *
p = -
; = +
/ = enter
h = _
y = .
