[global]
oneshot_timeout = 400
chord_timeout = 15  # for combos

[ids]
# kinesis advantage 2
29ea:0103
29ea:0102

include keyd_common
[main]
e+r = ~
d+f = {
c+v = `

r+t = +
f+g = }
v+b = backslash

y+u = -
h+j = "
n+m = |

u+i = :
j+k = equal
m+, = _

i+o = macro(--)

equal = +

a = lettermod(meta, a, 110, 200)
s = lettermod(shift, s, 110, 200)
d = lettermod(alt, d, 110, 200)
f = lettermod(control, f, 110, 200)

j = lettermod(control, j, 110, 200)
k = lettermod(alt, k, 110, 200)
l = lettermod(shift, l, 110, 200)
; = lettermod(meta, ;, 110, 200)

leftshift = oneshot(shift)
rightshift = oneshot(shift)

control = overload(control, escape)

escape = overload(control, escape)
delete = overload(keypad, delete)
tab = overload(keypad, tab)
enter = overload(control, enter)

[alt]
i = A-tab

[control]
m = enter
i = tab
[ = escape

[shift]
leftshift = {
rightshift = }

[keypad]
m = 1
, = 2
. = 3
j = 4
k = 5
l = 6
u = 7
i = 8
o = 9
enter = 0
8 = =
9 = /
0 = *
p = -
; = +
/ = enter
right = enter
down = ,
up = .
