#!/usr/bin/python
import os
import sys
import subprocess
import shlex


def run_command(command):
    tokenized_command = shlex.split(command)

    p = subprocess.Popen(tokenized_command,
                         stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)

    stdout = p.stdout.read()
    return stdout.rstrip(),


git_dir = run_command('git rev-parse --git-dir')

if not git_dir:
    sys.exit(1)

temp_tags = "{}/tags.temp".format(git_dir)
tags = "{}/tags".format(git_dir)

# remove the old temp file if for whatever reason it's still there
os.remove(temp_tags)

ctags_command = "ctags -R -o {} {}".format(temp_tags, git_dir + '/..')
run_command(ctags_command)
os.rename(temp_tags, tags)
