#!/bin/bash
# shellcheck disable=1090

# C Programming A Modern Approach - K.N. King. Start working on a chapter in
# a tmux session. Create the folder and copy a basic makefile if it's a new
# chapter.

MODERNC_PATH="$HOME/projects/c/modernc"

if [ -z "$1" ]
then
    echo "Please specify a chapter number to work on."
    exit 1
else
	CHAPTER="$1"
    SESSION="MC-CH$1"
fi

if ls "$MODERNC_PATH/$1_"* 1> /dev/null 2>&1; then
	list=("$MODERNC_PATH/$1_"*)
	# just use the first match
	WORKING_DIRECTORY="${list[0]}"
else
	echo "what is the name of the chapter? "; \
	read -r chapter_name; \
	chapter_name="${chapter_name//[![:alnum:]]/_}"
	WORKING_DIRECTORY="$MODERNC_PATH"/"$CHAPTER"_"${chapter_name,,}"
	mkdir "$WORKING_DIRECTORY"
fi

# Start a new session in the chapter folder
tmux new-session -d -c "$WORKING_DIRECTORY" -s "$SESSION"
# Start up vim and mark the pane to return to it later.
tmux send-keys "vim" C-m
# Split the window vertically, give it 20% of the window height.
# Start it in the same directory.
tmux split-window -v -p 20 -c "#{pane_current_path}"
# Add the bin folder to the path.
tmux send-keys "PATH=$WORKING_DIRECTORY/bin:$PATH" ENTER C-a C-l
# Return to the first pane
tmux select-pane -t :.0

tmux a -t "$SESSION"
