#!/bin/bash

# C Programming A Modern Approach - K.N. King. Start working on a chapter in
# a tmux session. Create the folder and copy a basic makefile if it's a new
# chapter.

MODERNC_PATH="$HOME/projects/c/modernc"

if [ -z "$1" ]
then
    echo "Please specify a chapter to work on."
    exit 1
else
    WORKING_DIRECTORY="$MODERNC_PATH/ch$1"
    SESSION="MC-ch$1"
fi

if [ ! -d $WORKING_DIRECTORY ];
then
    mkdir $WORKING_DIRECTORY
    cp "$MODERNC_PATH/ch2/Makefile" $WORKING_DIRECTORY
fi


# Start a new session in the chapter folder
tmux new-session -d -c $WORKING_DIRECTORY -s $SESSION
# Start up vim and mark the pane to return to it later.
tmux send-keys "vim" C-m
# Split the window vertically, give it 20% of the window height.
# Start it in the same directory.
tmux split-window -v -p 20 -c "#{pane_current_path}"
# Add the bin folder to the path.
tmux send-keys "PATH=$WORKING_DIRECTORY/bin:$PATH" ENTER C-a C-l
# Return to the first pane
tmux select-pane -t :.0

tmux a -t $SESSION
