#!/usr/bin/env bash

_NOTES_DIR=$HOME/notes

if [ "${1:-""}" = "--log" ]; then
    $EDITOR $_NOTES_DIR/log/$(date +%F).md
    exit
fi

while true; do
    files=$(find $_NOTES_DIR -type f ! -path "$_NOTES_DIR/.*/*" ! -name ".*")
    file="$(ls -t $files | \
        sed "s#$_NOTES_DIR/##" | \
        fzf --print-query \
        --select-1 \
        --preview="cat $_NOTES_DIR/{}" | \
        tail -n1 | \
        # remove leading new line
        xargs echo -n
    )"
    if [ -z "$file" ]; then
        break
    fi

    file="$_NOTES_DIR/$file"
    dir=$(dirname "$file")

    if [ ! -d "$dir" ]; then
        mkdir -p $dir
    fi

    $EDITOR $file
done
