#!/usr/bin/env bash

export GIT_PS1_STATESEPARATOR=":"
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export PROMPT_COMMAND="_prompt_command"
_prompt_command() {
    # Save the status before anything else so $? does not get overwritten.
    local EXIT=$? _status _autoenv_prompt _pwd
    # highlight with gray background.
    # local _hl="\[\e[48;5;237m\]"
    local _hl=""
    # reset all attributes
    # local _reset="\[\e[0m\]"
    local _reset=""

    if [ "$EXIT" != 0 ]; then
        _status="$EXIT "
    fi

    # only auto active environments in tmux sessions
    if [ -n "$TMUX" ]; then
        _autoenv

        if [ -n "$AUTOENV" ]; then
            if [ -z "$AUTOENV_PROMPT" ]; then
                _autoenv_prompt="$(basename $(dirname $AUTOENV))"
            else
                _autoenv_prompt="${AUTOENV_PROMPT}"
            fi
            _autoenv_prompt="${_hl}${_autoenv_prompt}${_reset} "
        fi
    fi

    _pwd=$(pwd | awk -F/ 'NF <= 3 { printf "%s", $0 } NF > 3 { printf "%s/%s", $(NF-1), $NF  }')

    __git_ps1 "${_status}${_autoenv_prompt}" "${_hl}${_pwd}${_reset} $ " "${_hl}%s${_reset} "

    # if [ -n "$TMUX" ]; then
    #     _pane_width=$(tmux display-message -p '#{pane_width}')
    #     if [ ${#PS1} -gt $(bc <<< "$_pane_width / 1.5") ]; then
    #         PS1="${PS1}\n$ "
    #     else
    #         PS1="${PS1} $ "
    #     fi
    # else
    #     PS1="${PS1} $ "
    # fi

    history -a  # Append new lines to history file
    history -c  # Clear the history list
    history -r  # Append the history file to the history list

    # Set the window title to $PWD
    # echo -ne "\033]0;$PWD\007"
}
