#!/usr/bin/python3

import sys
from subprocess import check_output

import i3ipc


def format_menu_item(container):
    fmt = '{ws.name}: {c.window_instance} - {c.name}'
    return fmt.format(ws=container.workspace(), c=container)


def call_rofi(containers):
    items = sorted([format_menu_item(c) for c in containers])
    cmd = ['rofi', '-l', str(len(items)), '-p', 'Focus: ', '-i', '-show', '-dmenu']
    menu_input = bytes(str.join('\n', items), 'UTF-8')
    pick = check_output(cmd, input=menu_input)
    return pick.strip().decode('UTF-8')


def handle_fullscreen(pick):
    fullscreen = pick.workspace().find_fullscreen()
    if fullscreen and fullscreen[0] != pick:
        fullscreen[0].command('fullscreen toggle')


if __name__ == '__main__':
    containers = i3ipc.Connection().get_tree().leaves()

    if not containers:
        sys.exit()

    if len(containers) == 1:
        pick = containers[0]
    else:
        pick = call_rofi(containers)
        pick = next(c for c in containers if format_menu_item(c) == pick)

    if pick:
        handle_fullscreen(pick)
        pick.command('focus')
